### ISSUE TITLE
updated Readme.md

### ISSUE THREAD

**Issue by dmoses** [jyobb/islandora_map_browse#1]
Hi John:
I've cleaned up and updated the readme file. https://github.com/dmoses/islandora_map_browse/blob/master/README.md ... let me know if that's ok and I'll submit a pull request. I've encountered a couple of issues during implementation and I'll create issues for those.
Don

**Comment by jyobb** [comment]
Don,

I really appreciate you doing this your improved README looks great.  I
would be glad to add it. I'll do my best to tackle any issues in a timely
manner.

John
