### ISSUE TITLE
Simple typo to fix in islandora_map_browse.module (I think)

### ISSUE THREAD

**Issue by petermacdonald** [jyobb/islandora_map_browse#13]
John:

I installed your module today, but then when I ran update.php, I got an error message from Drupal that it could not find the file "islandra_map_browse" (note the typo: "islandra"). This typo is in line 188 of the file "islandora_map_browse. module". When I fixed the typo in my module the error went away.

l. 188 $theme_registry['islandora_solr_wrapper']['theme path'] = drupal_get_path('module', 'islandra_map_browse') . '/theme';

Looks like a simple fix is in order.

Thanks,
Peter

**Comment by jyobb** [comment]
This has been fixed. Thanks for letting me know.
